### Numerical Python (NumPy)

In [2]:
# arrays

In [5]:
#!pip install numpy
import numpy as np # IMPORTING THE NUMPY LIBRARY (LOADING)

In [6]:
n = np.array([1,2,3])
n

array([1, 2, 3])

#### CREATING MULTIDIMENSIONAL ARRAYS

In [8]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
list_of_lists.shape

(3, 3)

#### NUMPY ARANGE

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [12]:
range(0,10,0.5) # The difference between numpy arange and range, the dont accept decimals

TypeError: 'float' object cannot be interpreted as an integer

#### NUMPY - ZEROS AND ONES

In [13]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [15]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [17]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(5,k = 1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.eye(5,k = -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [28]:
mn = np.arange(50)

mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [29]:
len(mn)

50

#### NUMPY RESHAPE

In [33]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [34]:
np.ones(6).reshape(2,3)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
mn.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

#### NUMPY LINSPACE

In [37]:
np.linspace(0,10,100) # Evenly spaced values

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

#### RESIZE

In [38]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [39]:
mn.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
mn.resize(5,10)

In [42]:
mn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
# Difference between resize and reshape
# The lenght of values should be the total values
# 1 * 50 values --> 5 * 10 = 50

#### RANDOM VALUES

In [48]:
print(np.random.rand(3,2))

"""Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``"""

[[0.45539805 0.16928066]
 [0.01891289 0.87271432]
 [0.72909703 0.08087261]]


'Create an array of the given shape and populate it with\nrandom samples from a uniform distribution\nover ``[0, 1)``'

In [54]:
print(np.random.randn(10))
"""Return a sample (or samples) from the "standard normal" distribution."""

[ 0.56919913 -2.29979555 -1.02695282 -0.38408192  0.79721989 -0.20170133
 -1.28894483  0.36691726 -0.71439902  0.08801867]


'Return a sample (or samples) from the "standard normal" distribution.'

In [52]:
print(np.random.randint(10))
"""Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`)."""

4


'Return random integers from the "discrete uniform" distribution of\nthe specified dtype in the "half-open" interval [`low`, `high`). If\n`high` is None (the default), then results are from [0, `low`).'

In [55]:
print(np.random.randint(0,100,10))

[45 88 76 91 19 76 90 46 21 51]


#### INDEXING AND SLICING

In [59]:
mn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [58]:
# find 27

mn[2][7]

27

In [64]:
mn[2:,7:]

array([[27, 28, 29],
       [37, 38, 39],
       [47, 48, 49]])

In [67]:
mn[mn>25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

#### BROADCASTING

In [69]:
mn[mn>25] = 25

In [70]:
mn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]])

In [71]:
mn[mn<25] = 0

In [72]:
mn

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]])

#### COPY - DEEP AND SHALLOW

In [76]:
true = np.arange(5)
true

array([0, 1, 2, 3, 4])

In [77]:
deep = true.copy()
deep

array([0, 1, 2, 3, 4])

In [79]:
deep[2:] = 0

In [80]:
deep

array([0, 1, 0, 0, 0])

In [81]:
true

array([0, 1, 2, 3, 4])

In [82]:
shallow = true
shallow

array([0, 1, 2, 3, 4])

In [84]:
shallow[2:] = 0

In [85]:
shallow

array([0, 1, 0, 0, 0])

In [86]:
true

array([0, 1, 0, 0, 0])

In [89]:
# the changes we do on the deep copy will not reflect on the original but for shallow copy, 
# the changes will replicate to the original data

#### DATAFRAME INTRODUCTION

In [90]:
# pd.read_csv --> Pandas --> Dataframe(multiple columns) and Series(single column)